// src/app/layout.tsx

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import WhatsAppButton from "../../components/floatingBtn";
import Script from "next/script";
import { Metadata } from "next";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "STELLAR BINGE",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <head>
        {/* Google Search Console verification */}
        <meta
          name="google-site-verification"
          content="dxj-iVuktppnnUldgn-dECo6FjjBkVmAMqzMsoF6Yx8"
        />
        <link rel="canonical" href="https://www.stellarbinge.com/" />

        {/* Google Analytics */}
        <Script
          strategy="afterInteractive"
          src="https://www.googletagmanager.com/gtag/js?id=G-G6GE5ZCT45"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-G6GE5ZCT45');
          `}
        </Script>

        {/* Microsoft Clarity */}
        <Script id="microsoft-clarity" strategy="afterInteractive">
          {`
            (function(c,l,a,r,i,t,y){
              c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
              t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;
              y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
            })(window, document, "clarity", "script", "t8im2kkd40");
          `}
        </Script>

        {/* Microsoft verification */}
        <meta name="msvalidate.01" content="A5873C26CCEEFFC7DEA52B82C10701C7" />

        {/* Google Tag Manager script */}
        <Script id="google-tag-manager" strategy="afterInteractive">
          {`
            (function(w,d,s,l,i){
              w[l]=w[l]||[];
              w[l].push({'gtm.start': new Date().getTime(), event:'gtm.js'});
              var f=d.getElementsByTagName(s)[0],
                  j=d.createElement(s), dl=l!='dataLayer'?'&l='+l:'';
              j.async=true;
              j.src='https://www.googletagmanager.com/gtm.js?id='+i+dl;
              f.parentNode.insertBefore(j,f);
            })(window,document,'script','dataLayer','GTM-WWCVMPW8');
          `}
        </Script>
        <Script
          id="structured-data"
          type="application/ld+json"
          strategy="afterInteractive"
        >
          {`
            {
              "@context": "https://schema.org",
              "@type": "Restaurant",
              "name": "Stellar Binge",
              "image": "https://www.stellarbinge.com/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Flogo.3fb31e53.png&w=384&q=75&dpl=dpl_98GvNudk4vhovL8VSVyNi3x1sRQD",
              "logo": "https://www.stellarbinge.com/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Flogo.3fb31e53.png&w=384&q=75&dpl=dpl_98GvNudk4vhovL8VSVyNi3x1sRQD",
              "address": {
                "@type": "PostalAddress",
                "streetAddress": "Ground Floor, Stellar IT Park, C-25, Sector 62",
                "addressLocality": "Noida",
                "postalCode": "201309",
                "addressCountry": "IN"
              },
              "telephone": "+91 9599816865",
              "servesCuisine": ["Indian", "Continental", "Multi-cuisine"],
              "url": "https://www.stellarbinge.com/",
              "priceRange": "₹₹",
              "openingHoursSpecification": [{
                "@type": "OpeningHoursSpecification",
                "dayOfWeek": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
                "opens": "11:00",
                "closes": "23:00"
              }],
              "sameAs": [
                "https://www.facebook.com/bingenoida",
                "https://www.instagram.com/stellar_binge",
                "https://www.youtube.com/@Stellar_Binge",
                "https://www.linkedin.com/in/stellar-binge-78691321a/"
              ]
            }
          `}
        </Script>
        {/* FAQ Structured Data */}
        <Script
          id="faq-structured-data"
          type="application/ld+json"
          strategy="afterInteractive"
        >
          {`
            {
              "@context": "https://schema.org",
              "@type": "FAQPage",
              "mainEntity": [
                {
                  "@type": "Question",
                  "name": "What are the opening hours of Stellar Binge?",
                  "acceptedAnswer": {
                    "@type": "Answer",
                    "text": "Stellar Binge is open daily from 11:00 AM to 11:00 PM."
                  }
                },
                {
                  "@type": "Question",
                  "name": "Do you accept reservations?",
                  "acceptedAnswer": {
                    "@type": "Answer",
                    "text": "Yes, you can reserve a table by calling +91 9599816865 or using the reservation form on our website."
                  }
                },
                {
                  "@type": "Question",
                  "name": "What cuisines are served at Stellar Binge?",
                  "acceptedAnswer": {
                    "@type": "Answer",
                    "text": "We serve a variety of cuisines including Indian, Continental, and Multi-cuisine dishes."
                  }
                },
                {
                  "@type": "Question",
                  "name": "Do you offer delivery or takeaway services?",
                  "acceptedAnswer": {
                    "@type": "Answer",
                    "text": "Yes, Stellar Binge offers both delivery and takeaway options. You can order directly through our website or contact us via phone."
                  }
                },
                {
                  "@type": "Question",
                  "name": "Is parking available at Stellar Binge?",
                  "acceptedAnswer": {
                    "@type": "Answer",
                    "text": "Yes, ample parking is available at our location in Stellar IT Park, Sector 62, Noida."
                  }
                },
                {
                  "@type": "Question",
                  "name": "Do you host events or private parties?",
                  "acceptedAnswer": {
                    "@type": "Answer",
                    "text": "Yes, Stellar Binge can host events, private parties, and corporate gatherings with customized arrangements and catering."
                  }
                }
              ]
            }
          `}
        </Script>
      </head>

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Google Tag Manager (noscript) */}
        <noscript>
          <iframe
            src="https://www.googletagmanager.com/ns.html?id=GTM-WWCVMPW8"
            height="0"
            width="0"
            style={{ display: "none", visibility: "hidden" }}
          ></iframe>
        </noscript>

        {children}
        <WhatsAppButton />
      </body>
    </html>
  );
}
